version: '3.5'

services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'